[package]
authors = ["frank <frank.049@hotmail.com>"]
name = "journaloo-server"
version = "0.1.0"
[dependencies]
dotenv = "*"
r2d2 = "*"
r2d2-diesel = "*"
rocket = "0.3.6"
rocket_codegen = "0.3.6"
rocket_contrib = "*"
chrono = "0.4.0"

[dependencies.diesel]
features = ["postgres", "chrono"]
version = "*"
